### ISSUE TITLE
WIP: Modernize CMake configuration

### ISSUE THREAD

**Issue by mloskot** [OSGeo/PROJ#1263]
**Status:** _Request For Comments_

Current configuration pre-dates CMake 3. Since the minimum required version of CMake bumped to 3.5 (#1262), it is possible to modernize the configuration following the **Modern CMake** approach and conventions in future versions of PROJ.4

Below, discussed are issues to consider. 

## BUILD_SHARED_LIBS

Remove custom `BUILD_LIBPROJ_SHARED` and rely on CMake native [BUILD_SHARED_LIBS](https://cmake.org/cmake/help/latest/variable/BUILD_SHARED_LIBS.html).

## Compiler flags management

It would be good to consider CMake modernisation to avoid manual fiddling with `CMAKE_CXX_FLAGS`.

Instead, there should be `add_library(proj4_compiler_flags INTERFACE)` followed by `target_compile_features`, `target_compile_options` etc. calls setting any generic features and compiler specific flags (using [generator expressions](https://cmake.org/cmake/help/latest/manual/cmake-generator-expressions.7.html)).

The `proj4_compiler_flags` target could also be accompanied with `proj4_compiler_flags_devel` extending the set of flags (e.g. with stricter warnings) for building PROJ.4 during development, CI testing, etc.

The `INTERFACE` targets approach is nowadays a recommended CMake way and https://gitlab.kitware.com/vtk/vtk-m or https://github.com/libgeos/geos/pull/130 can serve as working examples.

## C++ version requirement as usage requirement

Possible future refinements are discussed below as continuation of https://github.com/OSGeo/proj.4/issues/1118#issuecomment-463194388

> TBH, I'm not sure about setting `CXX_STANDARD` on any public targets, in the Config-files, etc.

The required C++ version required can also be imposed as usage requirement by setting compilation flags using CMake's [C++ features](https://cmake.org/cmake/help/v3.1/prop_gbl/CMAKE_CXX_KNOWN_FEATURES.html) requirement on the library target, in `src/lib_proj.cmake` file:

```
if(CMAKE_VERSION VERSION_LESS 3.8)
  target_compile_features(${PROJ_CORE_TARGET} INTERFACE cxx_nullptr)
else()
  target_compile_features(${PROJ_CORE_TARGET} INTERFACE cxx_std_11)
endif()
```

With that in place, installation will generate the following in both, `proj4-targets.cmake`  and `proj4-namespace-targets.cmake`:

```
set_target_properties(PROJ4::proj PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_11"
  ...
)
```

Then, the `cxx_std_11` effectively becomes a PROJ4 usage requirement effective wherever user calls:

```
target_link_libraries(proj4_client PRIVATE PROJ4::proj)
```

(NOTE: The `_link_` in `target_link_libraries` may be confusing and it's worth to remember `target_link_libraries` is not about linker flags only anymore.)

_**Implications**_ of the updated  `proj4-targets.cmake` and `proj4-namespace-targets.cmake` are:

1. Run `cmake` with defaults will build the client with `-std=c++11`
2. Run `cmake` with `-DCMAKE_CXX_STANDARD=17` will override `PROJ4::proj`'s default and build the client `-std=c++17` or `-std=gnu++17`, i.e. C++ version bumped accordingly
3. Run `cmake` with `-DCMAKE_CXX_STANDARD=98`, CMake will fallback to the default `-std=c++11`, then, if a compiler is not capable, the compilation will hopefully (**!**) fail. This is 

(**!**) The third case is _potentially dangerous_, because if the compiler is capable to compile, implicit change of C++11 version may have also switched to an [incompatible std:: string implementation](https://stackoverflow.com/a/49119902/151641); introduce ABI incompatibilities; mix objects/static library built with different version of compiler, etc.

## FindSQLite3.cmake

CMake 3.14 has got [new FindSQLite3.cmake](https://gitlab.kitware.com/cmake/cmake/merge_requests/2557). Copying into PROJ is a feasible solution.

...

-----

## Resources

* [An Introduction to Modern CMake](https://cliutils.gitlab.io/modern-cmake/) by Henry Schreiner
*  [Effective CMake](https://www.youtube.com/watch?v=bsXLMQ6WgIk) by Daniel Pfeifer

**Comment by mwtoews** [comment]
Just making a quick note of a particularly troublesome `CMAKE_CXX_FLAGS` fiddling is [here](https://github.com/OSGeo/proj.4/tree/7c9e460a4a8115553e6e4c71872bc2df1a45fb94/test/unit/CMakeLists.txt#L17-L18), which I've had to comment out when testing some obscure compiler. The error messages are:
```
CMake Error at test/unit/CMakeLists.txt:17 (string):
  string sub-command REGEX, mode REPLACE needs at least 6 arguments total to
  command.


CMake Error at test/unit/CMakeLists.txt:18 (string):
  string sub-command REGEX, mode REPLACE needs at least 6 arguments total to
  command.
```

**Comment by mloskot** [comment]
I haven't had chance to work on this. I'll let the stale bot close it for now and me or anyone can reopen whenever the work is continued.

**Comment by mwtoews** [comment]
Nah, this issue should stay open for a bit longer.

Here is a possible task list that I can see happen for PROJ 7.0:
- [x] Upgrade to at least CMake 3.9 ([see maillist](https://lists.osgeo.org/pipermail/proj/2020-January/009245.html))
- [ ] Change custom `BUILD_LIBPROJ_SHARED` in preference to CMake's [`BUILD_SHARED_LIBS`](https://cmake.org/cmake/help/latest/variable/BUILD_SHARED_LIBS.html); see #1858
- [x] Change custom `PROJ_TESTS` in preference to CTest's `BUILD_TESTING` variable (e.g. see [`enable_testing()`](https://cmake.org/cmake/help/latest/command/enable_testing.html), also this was recently refactored with GEOS 3.8)
- [ ] Rename `ENABLE_LTO` to `ENABLE_IPO`, and use [CheckIPOSupported](https://cmake.org/cmake/help/v3.9/module/CheckIPOSupported.html) to detect this compiler feature
- [x] Clean up `cmake/ProjUtilities.cmake`, to remove `colormsg` and `boost_report_value`, which appear redundant to the built-in `message()` function (correct me if I'm wrong), and a function with the name "boost" is possibly misleading
- [x] Consider renaming the CMake project name from `PROJ4` to `PROJ`; see #802 #1885 #1910
- [x] Fix `find_package(PROJ4 REQUIRED)` and/or `find_package(PROJ REQUIRED)` (which I possibly broke while renaming things); see #1484

**Comment by mloskot** [comment]
@mwtoews Your plan is sound to me
