### ISSUE TITLE
CMake configurations options to remove

### ISSUE THREAD

**Issue by mwtoews** [OSGeo/PROJ#1877]
These are CMake options to remove by PROJ 8.0:
- [x] `PROJ_TESTS` replaced by CTest's `BUILD_TESTING`; xref #1870
- [x] `ENABLE_LTO` replaced by `ENABLE_IPO`; xref #1952
- [x] `BUILD_LIBPROJ_SHARED` replaced by CMake's `BUILD_SHARED_LIBS`; xref #1962

**Comment by kbevers** [comment]
@mwtoews 8.0.0 is coming up soon - still want to take care of the above?

**Comment by mloskot** [comment]
Looks like the changes have already been applied, with only PR #2511 pending.
