### ISSUE TITLE
cmake full-transition memo

### ISSUE THREAD

**Issue by rouault** [OSGeo/PROJ#2688]
What is currently missing in cmake builds:

- [X]  `make dist` target - #2690
- [x] regeneration of src/wkt1_generated_parser.c/.h and src/wkt2_generated_parser.c/.h with bison : those are currently generated with "make wkt1_parser" and "make wkt2_parser" in the $builddir/src directory of a autoconf build: https://github.com/OSGeo/PROJ/pull/2900
- [x] check and migrate CI workflows, e.g. Clang Static Analyzer - #3001
- [x] migrate ossfuzz build: test/fuzzers/build.sh: tracked in https://github.com/OSGeo/PROJ/pull/2896
- [x] downstream users: GDAL CI && ossfuzz : tracked in https://github.com/OSGeo/gdal/issues/4576
- [X] downstream user: libgeotiff: https://github.com/OSGeo/libgeotiff/pull/64
- [x] Dockerfile (used by .github/workflows/docker.yml) needs to change to cmake: https://github.com/OSGeo/PROJ/pull/3018
- [x] revise `HOWTO-RELEASE` document for relevant changes - #3030
- [X] `make uninstall` target - https://github.com/OSGeo/PROJ/pull/3362
- [x] re-implement `PROJ_DB_CACHE_DIR` - #3711

**Comment by mwtoews** [comment]
Just by coincidence (within minutes from each other), see #2690 for "make dist"

**Comment by rouault** [comment]
>     * `make clean` target

What is missing exactly ? make clean seems to work

**Comment by mwtoews** [comment]
I can't recall, as `make clean` works fine from Makefile generators from CMake 3.10.2. I'll scrub this task off.

**Comment by mwtoews** [comment]
🤦 (facepalm) it was `make uninstall` that I was thinking of. Autotools supports this, although it is not tested. Any interest in bringing this to CMake too? It's not too difficult; see [how GEOS does this](https://github.com/libgeos/geos/blob/a434b1fbf6981bd6fd10dee1705fbf66b8e4fc0a/CMakeLists.txt#L394-L403).

**Comment by kbevers** [comment]
Sounds like a nice thing to have
